bridge_config:
  broker:
    driver: kombu
    amqp:
      host: 160.85.37.183
      port: 5672 
      user: tof
      password: Cloud4Robotics
      vhost: /
  endpoint:
#    alias: local
    topics:
      - collision_object
      - torso_controller/command
      - head_controller/command
      - planning_scene
      - planning_scene_world
      - move_group/monitored_planning_scene
      - attached_collision_object
    services:
      - apply_planning_scene
